parameters:
    guid: fhdkhfgskdgt-oydtghogb-dhgfjhgt
    installed: true
    databaseServer: localhost
    databaseUsername: craigray
    databasePassword: tiGGer44
    databaseName: craigray_kookaburra
    databasePort: '3306'
    caching: 1
    absoluteURL: 'https://bilby.craigrayner.com'
    security.hierarchy.roles:
        ROLE_USER: null
        ROLE_ALLOWED_TO_SWITCH: null
        ROLE_PARENT:
            - ROLE_USER
        ROLE_STUDENT:
            - ROLE_USER
        ROLE_STAFF:
            - ROLE_USER
        ROLE_TEACHER:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_STUDENT
            - ROLE_STAFF
        ROLE_HEAD_TEACHER:
            - ROLE_TEACHER
        ROLE_PRINCIPAL:
            - ROLE_HEAD_TEACHER
        ROLE_ADMIN:
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_STAFF
        ROLE_REGISTRAR:
            - ROLE_PRINCIPAL
            - ROLE_ADMIN
        ROLE_SYSTEM_ADMIN:
            - ROLE_REGISTRAR
            - ROLE_PARENT
    timezone: Australia/Sydney
    locale: en_GB
    mailer_dns: 'smtp://craig@craigrayner.com:sqhxicwdjcxvpxle@gmail'
    google_api_key: AIzaSyDxs2So92a--QPgNXfTYeAPK2EyVL4XZ2Q
    google_client_id: 869932302474-vmp86mrilkcn37s62vhrjpcdq2fu3ava.apps.googleusercontent.com
    google_client_secret: jqgOQUB_b2ms7DftqXvA4JSR
