parameters:
    guid: 'ec7cf8c20a8e02c8e0fa5f4919dfb233'
    installed: true
    databaseServer: 'localhost'
    databaseUsername: 'craigray'
    databasePassword: 'tiGGer44'
    databaseName: 'craigray_bilby'
    databasePort: 3306
    caching: 1
    absoluteURL: 'http://bilby.craigrayner.com'
