controllers:
    resource: ../../src/Controller/
    type: annotation


default_catch:
    path:     /{path}
    defaults:
        _controller: 'App\Controller\CatchController::index'
        path: /catch/
        permanent: true
    requirements:
        path: ".+"