default_catch:
    path:     /{path}
    condition: "request.getPathInfo() matches '@^(?!\/\_.*$).*@'"
    defaults:
        _controller: 'App\Controller\CatchController::index'
        path: /catch/
        permanent: true
    requirements:
        path: ".+"
    schemes: [ 'https' ]
