<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Crayner\Doctrine\CraynerDoctrineBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Kookaburra\SystemAdmin\KookaburraSystemAdminBundle::class => ['all' => true],
    Kookaburra\UserAdmin\KookaburraUserAdminBundle::class => ['all' => true],
    Kookaburra\Departments\KookaburraDepartmentsBundle::class => ['all' => true],
    Kookaburra\RollGroups\KookaburraRollGroupsBundle::class => ['all' => true],
    Kookaburra\Library\KookaburraLibraryBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
    Kookaburra\SchoolAdmin\KookaburraSchoolAdminBundle::class => ['all' => true],
    Kookaburra\Activities\KookaburraActivitiesBundle::class => ['all' => true],
];
