# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Form/Entity,Manager/Entity}'

    Gibbon\:
        resource: '../Gibbon/src/*'
        exclude: '../Gibbon/src/{Tests,Domain}'

    Gibbon\Domain\:
        resource: '../Gibbon/src/Domain/*'
        exclude: '../Gibbon/src/Domain/{Tests}'
        public: true

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    session:
        class: App\Session\GibbonSession
        public: true

    Gibbon\Contracts\Services\Session:
        alias: 'session'

    config:
        class: 'Gibbon\Core'
        arguments:
            $directory: '%kernel.project_dir%/Gibbon'
            $installed: '%installed%'
        public: true

    Gibbon\Core:
        alias: config

    locale:
        class: Gibbon\Locale
        arguments:
            $absolutePath: '%kernel.project_dir%/Gibbon'
        public: true

    page:
        class: Gibbon\View\Page
        arguments:
            $templateEngine: '@twig'
        public: true

    Gibbon\UI\Components\Header:
        public: true

    Gibbon\UI\Components\Sidebar:
        public: true

    action:
        class: App\Manager\ViewFactory
        factory: ['App\Manager\ViewFactory','getAction']

    module:
        class: App\Manager\ViewFactory
        factory: ['App\Manager\ViewFactory','getModule']

    App\Manager\GibbonManager:
        arguments:
            $version: '%version%'

    Gibbon\Forms\Form:
        factory: ['Gibbon\Forms\Form', 'create']

    Gibbon\Forms\FormFactory:
        public: true

    Gibbon\Forms\View\FormView:
        public: true
        arguments:
            - '@twig'

    Gibbon\Contracts\Database\Connection:
        factory: ['@App\Manager\LegacyConnectionFactory', 'createConnection']

    Gibbon\Module\Attendance\AttendanceView:
        public: true

    Gibbon\Forms\Prefab\BulkActionForm:
        public: true

    Gibbon\Forms\FormFactoryInterface:
        alias: Gibbon\Forms\FormFactory

    Gibbon\Forms\View\FormRendererInterface:
        alias: Gibbon\Forms\FormRenderer

    Gibbon\Tables\Prefab\RollGroupTable:
        public: true

    Gibbon\Module\Rubrics\Visualise:
        public: true
        arguments:
            $absoluteURL: '%absoluteURL%'

    Gibbon\Tables\DataTable:
        public: true

    Google_Service_Calendar:
        class: Google_Service_Calendar
        arguments:
            - '@Google_Client'
        public: true

    Gibbon\Tables\Prefab\ClassGroupTable:
        public: true

    App\Translation\Translator:
        decorates: translator

    App\Form\EventSubscriber\FileOrLinkURLSubscriber:
        arguments:
            $targetDir: '%kernel.public_dir%/%upload_path%'

    App\Manager\Entity\BreadCrumbs:
        class: App\Manager\Entity\BreadCrumbs

    monolog.formatter.importer:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.token%%] %%channel%%.%%level_name%%: %%message%% %%context%% %%extra%%\n"

    App\Logger\UserDetailProcessor:
        tags:
            - { name: monolog.processor }

    App\Router\KookaburraLoader:
        tags: [ routing.loader ]
